# CasaBot Wyoming Protocol Configuration Example
# Copy this file and rename it to match your add-on configuration needs

# Required: Your Azure OpenAI endpoint
azure_openai_endpoint: "https://your-resource.openai.azure.com/"

# Required: Your Azure OpenAI API key
azure_openai_api_key: "your-api-key-here"

# Optional: Azure OpenAI API version (default: 2024-02-01)
azure_openai_api_version: "2024-02-01"

# Optional: Whisper model to use (default: whisper-1)
# Available models depend on your Azure OpenAI deployment
model: "whisper-1"

# Optional: Language for transcription (default: auto)
# Use "auto" for automatic language detection
# or specify a language code like "en", "es", "fr", etc.
language: "auto"

# Optional: Wyoming protocol URI (default: tcp://0.0.0.0:11350)
wyoming_uri: "tcp://0.0.0.0:11350"

# Optional: Enable debug logging (default: false)
debug: false